// @no-log
POST http://localhost:9000/api/file/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="data.ovpn"
Content-Type: text/plain

< /Users/xiaowenrou/Documents/vpn/etar_openvpn.ovpn

--WebAppBoundary--

###

// @no-log
POST http://localhost:9000/api/admin/login
Content-Type: application/json

{"userName": "root", "password": "123456789"}

###

// @no-log
POST http://localhost:9000/api/admin/modify
Content-Type: application/json

{"userName": "root", "password": "123456", "newPassword": "123456789"}