server:
  port: 9000

spring:
  r2dbc:
    url: "r2dbc:mysql://47.254.34.47:3306/reactive_sale?characterEncoding=UTF-8&useSSL=false"
    username: "root"
    password: "123456"
    pool:
      enabled: true
      max-size: 30
      initial-size: 10
      validation-query: "select 1"
      max-idle-time: 300m
      max-acquire-time: 3s
      max-create-connection-time: 5s
  mail:
    # smtp服务器地址，例如 smtp.qq.com
    host: "smtp.exmail.qq.com"
    username: "eric.sun@earthmother.cn"
    # 这个是第三方登录邮箱的授权码
    password: "pLGaH4vKqNg3NcBM"

logging:
  level:
    org.springframework.http.codec.json.Jackson2JsonDecoder: trace
    org.springframework.core.codec.CharSequenceEncoder: trace

filePath: "/home/upload/"
targetMail: "sales@earthmother.cn"