server:
  port: 9000

#spring:
#  r2dbc:
#    url: "r2dbc:mysql://10.18.21.173:3306/marketing_ai_course?useUnicode=true&characterEncoding=UTF-8&useSSL=false"
#    username: "marketing_ai_course"
#    password: "Qn2574mdkM5CxJxd"
#    pool:
#      enabled: true
#      max-size: 30
#      initial-size: 10
#      validation-query: "select 1"
#      max-idle-time: 300m
#      max-acquire-time: 3s
#      max-create-connection-time: 5s

logging:
  level:
    org.springframework.http.codec.json.Jackson2JsonDecoder: trace
    org.springframework.core.codec.CharSequenceEncoder: trace

filePath: "/Users/xiaowenrou/Downloads/"